<?php

// Require

// Suggest

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'laravel\\serializableclosure\\contracts\\serializable' => '/Contracts/Serializable.php',
                'laravel\\serializableclosure\\contracts\\signer' => '/Contracts/Signer.php',
                'laravel\\serializableclosure\\exceptions\\invalidsignatureexception' => '/Exceptions/InvalidSignatureException.php',
                'laravel\\serializableclosure\\exceptions\\missingsecretkeyexception' => '/Exceptions/MissingSecretKeyException.php',
                'laravel\\serializableclosure\\exceptions\\phpversionnotsupportedexception' => '/Exceptions/PhpVersionNotSupportedException.php',
                'laravel\\serializableclosure\\serializableclosure' => '/SerializableClosure.php',
                'laravel\\serializableclosure\\serializers\\native' => '/Serializers/Native.php',
                'laravel\\serializableclosure\\serializers\\signed' => '/Serializers/Signed.php',
                'laravel\\serializableclosure\\signers\\hmac' => '/Signers/Hmac.php',
                'laravel\\serializableclosure\\support\\closurescope' => '/Support/ClosureScope.php',
                'laravel\\serializableclosure\\support\\closurestream' => '/Support/ClosureStream.php',
                'laravel\\serializableclosure\\support\\reflectionclosure' => '/Support/ReflectionClosure.php',
                'laravel\\serializableclosure\\support\\selfreference' => '/Support/SelfReference.php',
                'laravel\\serializableclosure\\unsignedserializableclosure' => '/UnsignedSerializableClosure.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd

// Files
